##
# BASH-UI - Bash User Interface Tools
# Copyright 2017 by Chad Juliano
# 
# Licensed under GNU Lesser General Public License v3.0 only. Some rights
# reserved. See LICENSE.
#
# File:         bui-themes.sh
# Description:  Theme templates used by bui-theme-mgr.sh
##

# There are 3 color spaces that can be used:
#   color16) 8 dark and 8 light colors (SGR_COL*)
#   HSL216) Hue/Saturation/Light (36x6x6) color space.
#   grey26) 26 shades of Grey. Much more than offered by HSL.

declare -ra THEME_TYPE_IMPACT=(
    [$THEME_CFG_DESC]='Impact (HSL 216)'
    [$THEME_CFG_BG_COLOR]="G26 3"
    [$THEME_CFG_DEF_COLOR]="HSL216 $((HSL216_HUE_YELLOW)) 4 5"
    [$THEME_CFG_SEL_COLOR]="HSL216 $((HSL216_HUE_BLUE - 3)) 3 5"
    [$THEME_CFG_SLI_COLOR]="HSL216 $((HSL216_HUE_RED + 3)) 3 3"
    [$THEME_CFG_SLA_COLOR]="HSL216 $((HSL216_HUE_RED + 3)) 1 5"
    [$THEME_CFG_DEF_ATTR]=0
    [$THEME_CFG_SEL_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLI_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLA_ATTR]=$THEME_ATTR_INVERT
)

declare -ra THEME_TYPE_BRIGHT=(
    [$THEME_CFG_DESC]="Bright"
    [$THEME_CFG_BG_COLOR]=$SGR_COL_BLACK
    [$THEME_CFG_DEF_COLOR]=$((SGR_COL_BLUE + SGR_ATTR_BRIGHT))
    [$THEME_CFG_SEL_COLOR]=$((SGR_COL_RED + SGR_ATTR_BRIGHT))
    [$THEME_CFG_SLI_COLOR]=$((SGR_COL_CYAN + SGR_ATTR_BRIGHT))
    [$THEME_CFG_SLA_COLOR]=$((SGR_COL_CYAN + SGR_ATTR_BRIGHT))
    [$THEME_CFG_DEF_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SEL_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLI_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLA_ATTR]=0
)

declare -ra THEME_TYPE_BRIGHT_216=(
    [$THEME_CFG_DESC]='Bright (HSL 216)'
    [$THEME_CFG_BG_COLOR]=$SGR_COL_BLACK
    [$THEME_CFG_DEF_COLOR]="HSL216 $((HSL216_HUE_BLUE - 4)) 3 4"
    [$THEME_CFG_SEL_COLOR]="HSL216 $((HSL216_HUE_BLUE - 4)) 2 5"
    [$THEME_CFG_SLI_COLOR]="HSL216 $((HSL216_HUE_RED + 3)) 1 3"
    [$THEME_CFG_SLA_COLOR]="HSL216 $((HSL216_HUE_RED + 3)) 1 5"
    [$THEME_CFG_DEF_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SEL_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLI_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLA_ATTR]=$THEME_ATTR_INVERT
)

declare -ra THEME_TYPE_MATRIX=(
    [$THEME_CFG_DESC]='Matrix (HSL 216)'
    [$THEME_CFG_BG_COLOR]="G26 2"
    [$THEME_CFG_DEF_COLOR]="HSL216 $((HSL216_HUE_GREEN)) 4 5"
    [$THEME_CFG_SEL_COLOR]="HSL216 $((HSL216_HUE_GREEN)) 1 3"
    [$THEME_CFG_SLI_COLOR]="HSL216 $((HSL216_HUE_GREEN)) 4 5"
    [$THEME_CFG_SLA_COLOR]="HSL216 $((HSL216_HUE_GREEN)) 1 3"
    [$THEME_CFG_DEF_ATTR]=0
    [$THEME_CFG_SEL_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLI_ATTR]=0
    [$THEME_CFG_SLA_ATTR]=$THEME_ATTR_INVERT
)

declare -ra THEME_TYPE_DARK=(
    [$THEME_CFG_DESC]='Dark'
    [$THEME_CFG_BG_COLOR]=$SGR_COL_BLACK
    [$THEME_CFG_DEF_COLOR]=$SGR_COL_WHITE
    [$THEME_CFG_SEL_COLOR]=$SGR_COL_RED
    [$THEME_CFG_SLI_COLOR]=$SGR_COL_WHITE
    [$THEME_CFG_SLA_COLOR]=$SGR_COL_WHITE
    [$THEME_CFG_DEF_ATTR]=0
    [$THEME_CFG_SEL_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLI_ATTR]=$THEME_ATTR_INVERT
    [$THEME_CFG_SLA_ATTR]=0
)

declare -ra THEME_TYPE_MONO=(
    [$THEME_CFG_DESC]='Monochrome'
    [$THEME_CFG_BG_COLOR]=$SGR_COL_DEFAULT
    [$THEME_CFG_DEF_COLOR]=$SGR_COL_DEFAULT
    [$THEME_CFG_SEL_COLOR]=$SGR_COL_DEFAULT
    [$THEME_CFG_SLI_COLOR]=$SGR_COL_DEFAULT
    [$THEME_CFG_SLA_COLOR]=$SGR_COL_DEFAULT
    [$THEME_CFG_DEF_ATTR]=0
    [$THEME_CFG_SEL_ATTR]=$SGR_ATTR_INVERT
    [$THEME_CFG_SLI_ATTR]=0
    [$THEME_CFG_SLA_ATTR]=$SGR_ATTR_INVERT
)

# make a list of all the themes
declare -ra THEME_LIST=(
    THEME_TYPE_IMPACT
    THEME_TYPE_BRIGHT
    THEME_TYPE_BRIGHT_216
    THEME_TYPE_MATRIX
    THEME_TYPE_DARK
    THEME_TYPE_MONO
)

declare -r THEME_DEFAULT_NAME='THEME_TYPE_IMPACT'
